#!/usr/bin/env bash
#Bash script that displays numbers from 1 to 100.

for c in {1..100}
do
	if (( $c%3 == 0  &&  $c%5 == 0 ))
	then   
	       	echo "FizzBuzz"
	elif (( $c % 3 == o ))
	then
		echo "Fizz"
	elif (( $c % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$c"
	fi
done
