#!/usr/bin/env bash
#Bash script that gives you information about the school file.

if [ -e "school" ]
then
       echo "school file exist"
       if [ -s "school" ]
       then
           echo "schoole file is not empty"
       else
           echo "schoole is empty"
       fi
       if [ -f "school" ]
       then
           echo " school is aregular file"
       fi
else
       echo "school file does not exist"
fi
